### ISSUE TITLE
enums: argument has incompatible type "int"; expected "ValueType"

### ISSUE THREAD

**Issue by jroitgrund** [nipunn1313/mypy-protobuf#367]
Given

```
enum MyEnum {
  A = 0;
  B = 1;
}

message MyMessage {
  MyEnum  my_enum = 1;
}
```

and

```
my_message = MyMessage(my_enum=0)
```

I get

> Argument "my_enum" to "MyMessage" has incompatible type "int"; expected "ValueType"

How can we pass int values to enums?

**Comment by nipunn1313** [comment]
There's some docs on it here
https://github.com/nipunn1313/mypy-protobuf#types-enum-int-values-more-strongly
mypy-protobuf takes the stance that the stubs should only accept strongly typed enum values - rather than pure ints.

There are a couple of ways. The most recommended is to use the actual enum type to get strong typing
```python
my_message = MyMessage(my_enum=MyEnum.A)
```

If you must use a pure int, you can do 
```python
MyMessage(my_enum=typing.cast('MyEnum.ValueType', 0))
```

And starting with protobuf 3.20 (released last week), you should be able to simplify to
```python
MyMessage(my_enum=MyEnum.ValueType(0))
```

**Comment by nipunn1313** [comment]
Going to close this one out! Reopen if this doesn't cover your issue.
