### ISSUE TITLE
Library stubs not installed for "google.protobuf.service_reflection"

### ISSUE THREAD

**Issue by devxpy** [nipunn1313/mypy-protobuf#425]
Type stubs not covered for https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/service_reflection.py

**Comment by nipunn1313** [comment]
Hi @devxpy. Thanks for the report. Can you provide some more information - a repro for the specific error you're seeing would be best.

The file you've linked (AFAICT) is not imported directly by the mypy-protobuf generated stubs. The non-generated google/protobuf code is part of typeshed here https://github.com/python/typeshed/tree/master/stubs/protobuf/google/protobuf - however, I don't think its contents are directly imported by calling code - so I'm not sure how you would have run into this error without more information.

**Comment by devxpy** [comment]
Looks like I found a workaround. Feel free to close if you don't think this is relevant.

---

I was importing -

```
google.protobuf.service_reflection.GeneratedServiceType
```

But this seems to do the same thing - 

```
from google.protobuf.service import Service
```

---

For context, here's what python returns as the type of a protobuf `service`
```
>>> type(community_affiliate_pb2.CommunityService)
google.protobuf.service_reflection.GeneratedServiceType
```


---


Thanks for this package and for your attention!

**Comment by nipunn1313** [comment]
yep! I believe you're right that `service_reflection.py` isn't typed (that would be an issue for typeshed here since it's not part of generated code (https://github.com/python/typeshed/tree/master/stubs/protobuf/google/protobuf).

However, AFAICT, `service_reflection` is only imported by generated code, so it's probably not very highly important to fix.

If it's important for you to import `service_reflection` directly, I'm sure that folks maintaining typeshed would take a PR.

**Comment by nipunn1313** [comment]
Thanks for the report
